spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
spring.datasource.username: root
spring.datasource.password: 11111111
spring.jpa.hibernate.use-new-id-generator-mappings: false
defaultPage: admin
sites:
  siteList:
    - url: https://dimonvideo.ru/
      name: dimonvideo
    - url: http://www.playback.ru/
      name: playback
fields:
  fieldList:
    - name: title
      selector: title
      weight: 1.0
    - name: body
      selector: body
      weight: 0.8
resultPageLimit: 100
newDB:
