spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
spring.datasource.username: root
spring.datasource.password: 11111111
defaultPage: admin
sites:
  siteList:
    - url: https://dimonvideo.ru/
      name: dimonvideo
    - url: http://www.playback.ru/
      name: playback
fields:
  fieldList:
    - name: title
      selector: title
      weight: 1.0
    - name: body
      selector: body
      weight: 0.8
#resultPageLimit: 20
newDB: false
